---
task_name: musdb18
train:
    input_source_types:
        - vocals
        - bass
        - drums
        - other
    target_source_types: 
        - vocals
        - bass
        - drums
        - other
    indexes_dict: "indexes/musdb18/sr=44100_ch=2/train/full_train/vocals_bass_drums_other.pkl"
    sample_rate: 44100
    channels: 2
    segment_seconds: 3.0
    model_type: UNet
    loss_type: l1_wav
    mini_data: False
    mixaudio:
        vocals: 1
        bass: 1
        drums: 1
        other: 1
    augmentation:
        pitch_shift: 0
    batch_data_preprocessor: BasicBatchDataPreprocessor
    evaluation_callback: Musdb18EvaluationCallback
    learning_rate: 1e-3
    batch_size: 16
    precision: 32
    steps_per_epoch: 10000  # Every 10000 steps is called an `epoch`.
    evaluate_step_frequency: 10000     # Evaluate every #evaluate_step_frequency steps.
    save_step_frequency: 50000  # Save every #save_step_frequency steps.
    early_stop_steps: 500001
    warm_up_steps: 1000
    reduce_lr_steps: 15000
    random_seed: 1234
    resume_checkpoint: ""

evaluate:
    train: "hdf5s/musdb18/sr=44100_ch=2/train/full_train"
    test: "hdf5s/musdb18/sr=44100_ch=2/test"
    segment_seconds: 30.0
    batch_size: 1